### ISSUE TITLE
Missing 'assets/' folder in 'web/' output

### ISSUE THREAD

**Issue by broadwell** [YaleDHLab/wordmap#6]
At present, it seems that one would need to obtain these files by scraping the demo site.

**Comment by broadwell** [comment]
Oh actually the `assets/` files are available in the source tree, but the necessity of cloning the repo *and* installing from `pip` is not exactly clear from the README.

**Comment by duhaime** [comment]
@broadwell thanks for your note and sorry about that! I guess the internal package structure changed but the packaging business didn't change with it. I just pushed some changes that should allow one to e.g.:

```
pip install wordmap -U
git clone https://github.com/duhaime/philosophical_transactions
wordmap --texts "philosophical_transactions/*.txt" --iter 2
```
to kick the tires...
