### ISSUE TITLE
Complaints about dependencies

### ISSUE THREAD

**Issue by broadwell** [YaleDHLab/wordmap#9]
I'm not sure if this is related to how the module is registered in PyPI or if I'm doing something wrong, but when I do `pip install wordmap` in a clean Python3 environment and then run the local version of `wordmap`, I get a `ModuleNotFoundError: No module named 'vertices'`.

After installing `vertices` manually, I then get a `ModuleNotFoundError: No module named 'tensorflow'` -- perhaps due to the use of `EpochLogger` in the code?

Installing `tensorflow` manually then leads to a `ImportError: cannot import name 'imread' from 'scipy.misc'` error, because it has overwritten the version of `scipy` specified for the module (1.1.0).

Forcing `scipy` back to 1.1.0 finally allows `wordmap` to run, but probably there's a pretty simple fix to avoid this runaround?

**Comment by duhaime** [comment]
Ahh, that's my bad. @pleonard212 just added vertices to the setup script, and I hadn't pushed changes up to pypi to make the updated setup available through `pip install`. 

If you have a moment, could I please ask you to try a `pip install wordmap -U` to pull down 0.1.3?

**Comment by broadwell** [comment]
Great, thanks! Despite the extra hassle involved, the availability of pypi packages is much appreciated.

**Comment by duhaime** [comment]
It's no trouble! I'm glad you sent the heads up that pypi needed updating!
